export const SET_INDIVIDUAL_PAGE = "SET_INDIVIDUAL_PAGE";

export const SET_ORGANIZATION_PAGE = "SET_ORGANIZATION_PAGE";

export const SET_ASSET_PAGE = "SET_ASSET_PAGE";

export const SET_INVESTOR_TYPE = "SET_INVESTOR_TYPE";

export const SET_ORGANIZATION_TYPE = "SET_ORGANIZATION_TYPE";

export const SET_PHONE_TYPE = "SET_PHONE_TYPE";

export const SET_REGISTER_TYPE = "SET_REGISTER_TYPE";

export const SET_REGISTER_ADMIN_TYPE = "SET_REGISTER_TYPE";

export const SET_WAITLIST_TYPE = "SET_WAITLIST_TYPE";

export const SET_DOWNLOAD_FORM_TYPE = "SET_DOWNLOAD_FORM_TYPE";
