export const SET_INDIVIDUAL_PAGE = 'SET_INDIVIDUAL_PAGE'

export const SET_ORGANIZATION_PAGE = 'SET_ORGANIZATION_PAGE'

export const SET_INVESTOR_TYPE = 'SET_INVESTOR_TYPE'

export const SET_ORGANIZATION_TYPE = 'SET_ORGANIZATION_TYPE'

